import { Id } from '../../shared/id/id';
import { NumberUtils } from '../../shared/utils/number-utils';
import { LearningTopic } from '../welcome/welcome.component';

export const prealgebraTarget = '9th grade';

export const subject = 'Prealgebra';

export const prealgebraTopics: LearningTopic[] = [
  {
    id: '2',
    title: 'Negative Numbers',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '3',
    title: 'Absolute Value',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '4',
    title: 'Divisibility and Factors',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '5',
    title: 'Prime Numbers',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '6',
    title: 'Prime Factorization',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '7',
    title: 'Least Common Multiple',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: '8',
    title: 'Greatest Common Factor',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Decimals and Place Notation',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Using Decimals in Math',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Decimals on a Number Line',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Understanding Fractions',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Equivalent Fractions and Simplifying',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Comparing Fractions',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Decomposing Fractions',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Fractions with Different Denominators',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Ratios and Proportions',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Rates',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Unit Conversions',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Metric System Unit Conversion',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Exponents',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Square Root',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Cube Root',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Scientific Notation',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Place Value',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Rounding Whole Numbers',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Rational and Irrational Numbers',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
  {
    id: Id.uuid.generateInBase62(),
    title: 'Order of Operations',
    topicQuestionList: [],
    progress: NumberUtils.getRandomInt(0, 100),
    hours: NumberUtils.getRandomInt(0, 5),
  },
];
